// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f00069f9-b16a-4e56-b199-e81240fdb84a";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onServoScheduleChange();
void onServoSchedule2Change();
void onAirSangatKeruhChange();
void onModeChange();
void onPakanHabisChange();
void onServoSwitchChange();

String statusAir;
String statusPakan;
String statusServo;
float distance;
float ntuValue;
float persenPakan;
CloudSchedule servoSchedule;
CloudSchedule servoSchedule2;
bool airSangatKeruh;
bool mode;
bool pakanHabis;
bool servoSwitch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(statusAir, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(statusPakan, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(statusServo, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(distance, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ntuValue, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(persenPakan, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(servoSchedule, READWRITE, ON_CHANGE, onServoScheduleChange);
  ArduinoCloud.addProperty(servoSchedule2, READWRITE, ON_CHANGE, onServoSchedule2Change);
  ArduinoCloud.addProperty(airSangatKeruh, READWRITE, ON_CHANGE, onAirSangatKeruhChange);
  ArduinoCloud.addProperty(mode, READWRITE, ON_CHANGE, onModeChange);
  ArduinoCloud.addProperty(pakanHabis, READWRITE, ON_CHANGE, onPakanHabisChange);
  ArduinoCloud.addProperty(servoSwitch, READWRITE, ON_CHANGE, onServoSwitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
